# Generated by Django 3.2.6 on 2021-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('DESCRIPTION', models.TextField(max_length=100)),
                ('UUID', models.CharField(max_length=10)),
                ('CREATED', models.ImageField(upload_to='uploads/')),
                ('ROTATE_DURATION', models.CharField(max_length=50)),
            ],
        ),
    ]
