# Generated by Django 3.2.6 on 2021-08-02 18:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_auto_20210802_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CREATED',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='LOGO',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ROTATE_DURATION',
            new_name='rotate_duration',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='UUID',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='UPDATED',
        ),
        migrations.AddField(
            model_name='product',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
