# Generated by Django 3.2.6 on 2021-08-02 19:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_rename_is_edited_product_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
