# Generated by Django 3.2.6 on 2021-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_auto_20210802_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.CharField(default=123, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
