# Generated by Django 3.2.6 on 2021-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_auto_20210802_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
