# Generated by Django 3.2.6 on 2021-08-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rotate_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
